webtalk_init -webtalk_dir /home/patricio/Facultad/arqui/practico/arqui-alu/tp1/tp1.sim/sim_1/behav/xsim/xsim.dir/alu_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 21 18:42:24 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "46585f98-5f15-420e-a0c4-5eca493b2405" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "292bfd3cf49b44f5b170b7b8bea0fe79" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "330 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.36_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116716_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1666960802 -regid "" -xml /home/patricio/Facultad/arqui/practico/arqui-alu/tp1/tp1.sim/sim_1/behav/xsim/xsim.dir/alu_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/patricio/Facultad/arqui/practico/arqui-alu/tp1/tp1.sim/sim_1/behav/xsim/xsim.dir/alu_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/patricio/Facultad/arqui/practico/arqui-alu/tp1/tp1.sim/sim_1/behav/xsim/xsim.dir/alu_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
